- the Windows DLLs can now be built for both x86_64 and i686 architectures - added Linux and Windows build.sh scripts that copy artefacts to local directory similarly to macOS - removed cmake support files as they are now integrated in the Windows Dockerfile

diff --git a/build_recipes/windows/Dockerfile_windows b/build_recipes/windows/Dockerfile_windows
--- a/build_recipes/windows/Dockerfile_windows
+++ b/build_recipes/windows/Dockerfile_windows
@@ -1,17 +1,64 @@
 
-# To build an image with this Dockerfile:
-# docker build -t rdkit-knime-win-x86_64 -f Dockerfile_win_x86_64 --network=host $@ .
+# Build Windows RDKit Java and C# DLLs for ARCH, where ARCH={x86_64|i686}
 
-# To run bash in the built image mounting a local dir inside the container:
-# mkdir -p knime_dlls && docker run -u root --network=host --mount type=bind,source="$(pwd)/knime_dlls,target=/knime_dlls -it rdkit-knime-win:latest bash
+ARG ARCH="x86_64"
+ARG DEPS="/deps"
+ARG WORK="/work"
+ARG SRC="/src"
+ARG IMAGE="/image"
+ARG RDKIT_RELEASE="2022_09_2"
+ARG RDKIT_CHKSUM="052d9eae42da57d5af91e9d06d3b4de1"
 
-FROM fedora:36 AS GCC_TOOL_CHAIN
+FROM fedora:36 AS build-stage-prep
+ARG ARCH
+ARG DEPS
+ARG WORK
+ARG SRC
+ARG IMAGE
+
+RUN echo "Building Windows ${ARCH} Java and C# DLLs"
+RUN [ "${ARCH}" = x86_64 ] || [ "${ARCH}" = i686 ] || \
+    ( echo "FAILED - please set ARCH to x86_64 or i686." 1>&2 && exit 1 )
 
 USER root
 
+RUN dnf update -y
+RUN dnf install -y patch bzip2 ca-certificates openssl openssl-devel java-1.8.0-openjdk-devel \
+    mono-devel make gcc gcc-c++
+
+RUN groupadd -g 1005 docker && \
+    useradd -u 1005 -s /bin/bash -g docker docker && \
+    mkdir ${SRC} ${WORK} ${IMAGE} ${DEPS} && \
+    chown -R docker:docker ${SRC} ${WORK} ${IMAGE} ${DEPS}
+RUN mkdir -p /home/docker && chown docker:docker /home/docker
+USER docker
+
+FROM build-stage-prep AS build-stage-x86_64
+ARG ARCH
+ENV BITS="64"
+ENV ZLIB_ARCH_SWITCH="--64"
+ENV SWIG_STDCALL_SWITCH=""
+
+FROM build-stage-prep AS build-stage-i686
+ARG ARCH
+ENV BITS="32"
+ENV ZLIB_ARCH_SWITCH=""
+ENV SWIG_STDCALL_SWITCH="-Wl,--add-stdcall-alias"
+
+FROM build-stage-${ARCH} AS build-stage
+ARG ARCH
+
+USER root
+RUN dnf install -y mingw${BITS}-gcc mingw${BITS}-gcc-c++ mingw${BITS}-runtime mingw${BITS}-winpthreads-static
+USER docker
+
+ARG DEPS
+ARG WORK
+ARG SRC
+ARG IMAGE
 ARG BUILD_CONCURRENCY="6"
-ARG RDKIT_RELEASE="2022_09_2"
-ARG RDKIT_CHKSUM="052d9eae42da57d5af91e9d06d3b4de1"
+ARG RDKIT_RELEASE
+ARG RDKIT_CHKSUM
 ARG ZLIB_VERSION="1.2.13"
 ARG ZLIB_CHKSUM="9b8aa094c4e5765dabf4da391f00d15c"
 ARG BZIP2_VERSION="1.0.8"
@@ -32,21 +79,7 @@ ARG PIXMAN_VERSION="0.42.0"
 ARG PIXMAN_CHKSUM="d925aa9e9ed9d419b6c2e02a61a11d29"
 ARG CAIRO_VERSION="1.16.0"
 ARG CAIRO_CHKSUM="f19e0353828269c22bd72e271243a552"
-ARG DEPS="/deps"
-ARG WORK="/work"
-ARG SRC="/src"
-ARG IMAGE="/image"
 
-RUN dnf update -y
-RUN dnf install -y patch bzip2 ca-certificates openssl openssl-devel java-1.8.0-openjdk-devel \
-    mono-devel mingw64-gcc mingw64-gcc-c++ mingw64-runtime make gcc gcc-c++ mingw64-winpthreads-static
-
-RUN groupadd -g 500 docker && \
-    useradd -u 500 -s /bin/bash -g docker docker && \
-    mkdir ${SRC} ${WORK} ${IMAGE} ${DEPS} && \
-    chown -R docker:docker ${SRC} ${WORK} ${IMAGE} ${DEPS}
-RUN mkdir -p /home/docker && chown docker:docker /home/docker
-USER docker
 RUN mkdir -p ${WORK}/boost ${WORK}/cmake ${WORK}/eigen ${WORK}/zlib ${WORK}/bzip2 ${WORK}/freetype ${WORK}/swig ${WORK}/cairo
 
 WORKDIR ${WORK}/zlib
@@ -55,7 +88,7 @@ RUN curl -L -O https://zlib.net/zlib-${ZLIB_VERSION}.tar.gz && \
     ( >&2 echo "Failed to download zlib" && exit 1 )
 RUN tar xzf zlib-${ZLIB_VERSION}.tar.gz
 WORKDIR ${WORK}/zlib/zlib-${ZLIB_VERSION}
-RUN AR="x86_64-w64-mingw32-ar" CC="x86_64-w64-mingw32-gcc -fPIC" ./configure --static --64 --prefix=${DEPS}
+RUN AR="${ARCH}-w64-mingw32-ar" CC="${ARCH}-w64-mingw32-gcc -fPIC" ./configure --static ${ZLIB_ARCH_SWITCH} --prefix=${DEPS}
 RUN make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install
 
 WORKDIR ${WORK}/bzip2
@@ -64,7 +97,7 @@ RUN curl -L -O https://sourceware.org/pub/bzip2/bzip2-${BZIP2_VERSION}.tar.gz &&
     ( >&2 echo "Failed to download bzip2" && exit 1 )
 RUN tar xzf bzip2-${BZIP2_VERSION}.tar.gz
 WORKDIR ${WORK}/bzip2/bzip2-${BZIP2_VERSION}
-RUN make AR="x86_64-w64-mingw32-ar" CC="x86_64-w64-mingw32-gcc -fPIC" PREFIX=${DEPS} -j${BUILD_CONCURRENCY} libbz2.a
+RUN make AR="${ARCH}-w64-mingw32-ar" CC="${ARCH}-w64-mingw32-gcc -fPIC" PREFIX=${DEPS} -j${BUILD_CONCURRENCY} libbz2.a
 RUN cp bzlib.h ${DEPS}/include && cp libbz2.a ${DEPS}/lib
 
 WORKDIR ${WORK}/boost
@@ -73,11 +106,11 @@ RUN curl -L -O https://boostorg.jfrog.io/artifactory/main/release/`echo ${BOOST_
     ( >&2 echo "Failed to download boost" && exit 1 )
 RUN tar xjf boost_${BOOST_VERSION}.tar.bz2
 WORKDIR ${WORK}/boost/boost_${BOOST_VERSION}
-RUN echo 'using gcc : mingw : x86_64-w64-mingw32-g++ ;' > user-config.jam
+RUN echo "using gcc : mingw : ${ARCH}-w64-mingw32-g++ ;" > user-config.jam
 RUN ./bootstrap.sh --with-toolset=gcc \
     --with-libraries=serialization,iostreams,regex,system --without-icu --prefix=${DEPS}
 RUN ./b2 --user-config=./user-config.jam toolset=gcc-mingw \
-        target-os=windows address-model=64 architecture=x86 \
+        target-os=windows address-model=${BITS} architecture=x86 \
         cflags=-fPIC cxxflags=-fPIC --prefix=${WORK}/boost/install variant=release link=static \
         --with-serialization --with-iostreams --with-regex --with-system \
         -sBZIP2_INCLUDE=${DEPS}/include -sBZIP2_LIBPATH=${DEPS}/lib \
@@ -125,10 +158,10 @@ RUN curl -L -O https://download.savannah.gnu.org/releases/freetype/freetype-${FR
     ( >&2 echo "Failed to download freetype" && exit 1 )
 RUN tar xzf freetype-${FREETYPE_VERSION}.tar.gz
 WORKDIR ${WORK}/freetype/freetype-${FREETYPE_VERSION}
-RUN CC="x86_64-w64-mingw32-gcc -fPIC -I${DEPS}/include" \
-    CXX="x86_64-w64-mingw32-g++ -fPIC -I${DEPS}/include" AR="x86_64-w64-mingw32-ar" \
+RUN CC="${ARCH}-w64-mingw32-gcc -fPIC -I${DEPS}/include" \
+    CXX="${ARCH}-w64-mingw32-g++ -fPIC -I${DEPS}/include" AR="${ARCH}-w64-mingw32-ar" \
     LDFLAGS="-L${DEPS}/lib" PKG_CONFIG_PATH=${DEPS}/lib/pkgconfig \
-    ./configure --host=x86_64-w64-mingw32 --build=x86_64-pc-linux-gnu \
+    ./configure --host=${ARCH}-w64-mingw32 --build=${ARCH}-pc-linux-gnu \
     --enable-static=yes --enable-shared=no --prefix=${DEPS}
 RUN make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install
 
@@ -140,9 +173,9 @@ RUN for i in `seq 1 5`; do \
 RUN test -e libpng_md5_ok || ( >&2 echo "Failed to download libpng" && exit 1 )
 RUN tar xzf libpng-${LIBPNG_VERSION}.tar.gz
 WORKDIR ${WORK}/cairo/libpng-${LIBPNG_VERSION}
-RUN CC="x86_64-w64-mingw32-gcc -fPIC -I${DEPS}/include" AR="x86_64-w64-mingw32-ar" \
+RUN CC="${ARCH}-w64-mingw32-gcc -fPIC -I${DEPS}/include" AR="${ARCH}-w64-mingw32-ar" \
     LDFLAGS="-L${DEPS}/lib" PKG_CONFIG_PATH=${DEPS}/lib/pkgconfig \
-    ./configure --host=x86_64-w64-mingw32 --build=x86_64-pc-linux-gnu \
+    ./configure --host=${ARCH}-w64-mingw32 --build=${ARCH}-pc-linux-gnu \
     --enable-shared=no --enable-static=yes --prefix=${DEPS}
 RUN make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install
 
@@ -152,9 +185,9 @@ RUN curl -L -O https://www.cairographics.org/releases/pixman-${PIXMAN_VERSION}.t
     ( >&2 echo "Failed to download pixman" && exit 1 )
 RUN tar xzf pixman-${PIXMAN_VERSION}.tar.gz
 WORKDIR ${WORK}/cairo/pixman-${PIXMAN_VERSION}
-RUN CC="x86_64-w64-mingw32-gcc -fPIC -I${DEPS}/include" AR="x86_64-w64-mingw32-ar" \
+RUN CC="${ARCH}-w64-mingw32-gcc -fPIC -I${DEPS}/include" AR="${ARCH}-w64-mingw32-ar" \
     LDFLAGS="-L${DEPS}/lib" PKG_CONFIG_PATH=${DEPS}/lib/pkgconfig \
-    ./configure --host=x86_64-w64-mingw32 --build=x86_64-pc-linux-gnu \
+    ./configure --host=${ARCH}-w64-mingw32 --build=${ARCH}-pc-linux-gnu \
     --enable-shared=no --enable-static=yes --prefix=${DEPS}
 RUN make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install
 
@@ -164,10 +197,10 @@ RUN curl -L -O https://www.cairographics.org/releases/cairo-${CAIRO_VERSION}.tar
     ( >&2 echo "Failed to download cairo" && exit 1 )
 RUN tar xJf cairo-${CAIRO_VERSION}.tar.xz
 WORKDIR ${WORK}/cairo/cairo-${CAIRO_VERSION}
-RUN CC="x86_64-w64-mingw32-gcc -fPIC -I${DEPS}/include" \
-    CXX="x86_64-w64-mingw32-g++ -fPIC -I${DEPS}/include" AR="x86_64-w64-mingw32-ar" \
+RUN CC="${ARCH}-w64-mingw32-gcc -fPIC -I${DEPS}/include" \
+    CXX="${ARCH}-w64-mingw32-g++ -fPIC -I${DEPS}/include" AR="${ARCH}-w64-mingw32-ar" \
     PKG_CONFIG_PATH=${DEPS}/lib/pkgconfig LDFLAGS="-L${DEPS}/lib -Bstatic -lssp -Bdynamic" \
-    ./configure --host=x86_64-w64-mingw32 --build=x86_64-pc-linux-gnu \
+    ./configure --host=${ARCH}-w64-mingw32 --build=${ARCH}-pc-linux-gnu \
     --enable-shared=no --enable-static=yes --prefix=${DEPS}
 RUN make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install
 
@@ -177,16 +210,16 @@ RUN curl -L -O https://github.com/rdkit/rdkit/archive/refs/tags/Release_${RDKIT_
     ( >&2 echo "Failed to download RDKit" && exit 1 )
 RUN tar xzf Release_${RDKIT_RELEASE}.tar.gz
 WORKDIR ${SRC}/rdkit-Release_${RDKIT_RELEASE}
-COPY --chown=docker:docker win-x86_64.cmake ${SRC}/rdkit-Release_${RDKIT_RELEASE}/
+#COPY --chown=docker:docker win-${ARCH}.cmake ${SRC}/rdkit-Release_${RDKIT_RELEASE}/
 RUN sed -i "s|#if _MSC_VER|#ifdef _WIN32|" Code/GraphMol/catch_chirality.cpp
 RUN sed -i "s|Windows\.h|windows.h|" Code/GraphMol/MMPA/MMPA_UnitTest.cpp
-RUN sed -i -e "s|\( *\)\(target_link_libraries(MolDraw2D PUBLIC \)\(Cairo::Cairo\)|\1target_include_directories(MolDraw2D PUBLIC ${DEPS}/include/cairo)\n\1\2 ${DEPS}/lib/libcairo.a /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libssp.a ${DEPS}/lib/libpixman-1.a ${DEPS}/lib/libpng16.a|" \
+RUN sed -i -e "s|\( *\)\(target_link_libraries(MolDraw2D PUBLIC \)\(Cairo::Cairo\)|\1target_include_directories(MolDraw2D PUBLIC ${DEPS}/include/cairo)\n\1\2 ${DEPS}/lib/libcairo.a /usr/${ARCH}-w64-mingw32/sys-root/mingw/lib/libssp.a ${DEPS}/lib/libpixman-1.a ${DEPS}/lib/libpng16.a|" \
     -e "s|\( *\)\(target_link_libraries(MolDraw2D PUBLIC \)\(.*\)\()\)|\1\2\3 ${DEPS}/lib/libz.a ${DEPS}/lib/libbz2.a\4|" \
     Code/GraphMol/MolDraw2D/CMakeLists.txt
 RUN sed -i -e "s|if(WIN32)|if(FALSE)|" \
-    -e "s|\(SWIG_LINK_LIBRARIES *( *\)\(GraphMolWrap *\)\(\${RDKit_Wrapper_Libs}\)|\1\2-static -static-libgcc -static-libstdc++ \3 /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libssp.a ${DEPS}/lib/libz.a ${DEPS}/lib/libbz2.a ${DEPS}/lib/libpixman-1.a ${DEPS}/lib/libpng16.a|" \
+    -e "s|\(SWIG_LINK_LIBRARIES *( *\)\(GraphMolWrap *\)\(\${RDKit_Wrapper_Libs}\)|\1\2-static -static-libgcc -static-libstdc++ ${SWIG_STDCALL_SWITCH} \3 /usr/${ARCH}-w64-mingw32/sys-root/mingw/lib/libssp.a ${DEPS}/lib/libz.a ${DEPS}/lib/libbz2.a ${DEPS}/lib/libpixman-1.a ${DEPS}/lib/libpng16.a|" \
     Code/JavaWrappers/gmwrapper/CMakeLists.txt
-RUN sed -i "s|\(SWIG_LINK_LIBRARIES *( *\)\(RDKFuncs *\)\(\${RDKit_Wrapper_Libs}\)|\1\2-static -static-libgcc -static-libstdc++ \3 /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libssp.a ${DEPS}/lib/libz.a ${DEPS}/lib/libbz2.a ${DEPS}/lib/libpixman-1.a ${DEPS}/lib/libpng16.a|" \
+RUN sed -i "s|\(SWIG_LINK_LIBRARIES *( *\)\(RDKFuncs *\)\(\${RDKit_Wrapper_Libs}\)|\1\2-static -static-libgcc -static-libstdc++ ${SWIG_STDCALL_SWITCH} \3 /usr/${ARCH}-w64-mingw32/sys-root/mingw/lib/libssp.a ${DEPS}/lib/libz.a ${DEPS}/lib/libbz2.a ${DEPS}/lib/libpixman-1.a ${DEPS}/lib/libpng16.a|" \
     Code/JavaWrappers/csharp_wrapper/CMakeLists.txt
 
 # Patch to remove the dependency on msvcrt120.dll
@@ -202,6 +235,21 @@ RUN sed -i -e "s|set(AVALON_VERSION \"2\.0\.2\")|set(AVALON_VERSION \"2.0.4a\")|
 # Patch for SWIG loggers
 RUN sed -i "s|^\(.include <RDGeneral/\)\(versions.h>\)|\1\2\n\1RDLog.h>|" Code/JavaWrappers/gmwrapper/GraphMolJava.i
 RUN sed -i "s|^\(.include <RDGeneral/\)\(versions.h>\)|\1\2\n\1RDLog.h>|" Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
+
+RUN echo > win-${ARCH}.cmake -e \
+    "set(CMAKE_SYSTEM_NAME Windows)\n" \
+    "set(CMAKE_SYSTEM_VERSION 1)\n" \
+    "set(CMAKE_SYSTEM_PROCESSOR ${ARCH})\n" \
+    "set(TOOLCHAIN_PREFIX ${ARCH}-w64-mingw32)\n" \
+    "\n" \
+    "set(CMAKE_C_COMPILER     "\${TOOLCHAIN_PREFIX}-gcc")\n" \
+    "set(CMAKE_CXX_COMPILER   "\${TOOLCHAIN_PREFIX}-g++")\n" \
+    "\n" \
+    "set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)\n" \
+    "set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)\n" \
+    "set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)\n" \
+    "\n" \
+    "set(CMAKE_CROSS_COMPILING TRUE)\n"
 
 RUN mkdir build
 WORKDIR ${SRC}/rdkit-Release_${RDKIT_RELEASE}/build
@@ -238,7 +286,7 @@ RUN export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk && \
     -D CAIRO_INCLUDE_DIR=${DEPS}/include/cairo \
     -D CAIRO_LIBRARY_DIR=${DEPS}/lib \
     -D CMAKE_INSTALL_PREFIX=${IMAGE} \
-    -D CMAKE_TOOLCHAIN_FILE=$PWD/../win-x86_64.cmake \
+    -D CMAKE_TOOLCHAIN_FILE=$PWD/../win-${ARCH}.cmake \
     -D JAVA_AWT_LIBRARY="${JAVA_HOME}/lib/amd64/libjawt.so" \
     -D JAVA_JVM_LIBRARY="${JAVA_HOME}/jre/lib/amd64/server/libjvm.so" \
     -D JAVA_INCLUDE_PATH="${JAVA_HOME}/include" \
@@ -246,3 +294,13 @@ RUN export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk && \
     -D JAVA_AWT_INCLUDE_PATH="${JAVA_HOME}/include" \
     ..
 RUN make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install
+
+FROM scratch as export-stage
+ARG ARCH
+ARG SRC
+ARG RDKIT_RELEASE
+COPY --from=build-stage ${SRC}/rdkit-Release_${RDKIT_RELEASE}/Code/JavaWrappers/gmwrapper/org.RDKit.jar /${ARCH}/org.RDKit.jar
+COPY --from=build-stage ${SRC}/rdkit-Release_${RDKIT_RELEASE}/Code/JavaWrappers/gmwrapper/org.RDKitDoc.jar /${ARCH}/org.RDKitDoc.jar
+COPY --from=build-stage ${SRC}/rdkit-Release_${RDKIT_RELEASE}/Code/JavaWrappers/gmwrapper/GraphMolWrap.dll /${ARCH}/GraphMolWrap.dll
+COPY --from=build-stage ${SRC}/rdkit-Release_${RDKIT_RELEASE}/Code/JavaWrappers/csharp_wrapper/RDKFuncs.dll /${ARCH}/RDKFuncs.dll
+COPY --from=build-stage ${SRC}/rdkit-Release_${RDKIT_RELEASE}/Code/JavaWrappers/csharp_wrapper/RDKit2DotNet.dll /${ARCH}/RDKit2DotNet.dll
